 <?php
use Admin\Lib\Ioline;

$flagnew=false;
//выделим идентифатор строки из параметра save -он всегда есть
if(isset($_POST["save"])){
    $id=array_keys($_POST["save"]);
    $id=$id[0];
} 
if(isset($_POST["saveadd"])){
    $id=array_keys($_POST["saveadd"]);
    $id=$id[0];
    //$flagnew=true;
} 
if ($id==0){
    //у нас добавление нового товара, фиктивно обратимся к базовому интерфейсу
    //что бы он создал новую запись
    $io_line_interface=new Ioline($this->container,$this);
    $io_line_interface->create_interface("create_catalog_tovar_base", false);
    //получим ID новой записи
    $id=$io_line_interface->last_insert_id;
    //перезапишем массив POST, что бы другие интерфейсы поняли откуда брать данные
    foreach ($_POST as $k=>$p){
        if (is_array($p)){
            $_POST[$k]=[$id=>$p[0]];
            unset($_POST[$k][0]);
        }
    $_GET['get_interface_input'] = base64_encode(serialize($id));
    }

}
/*это имитация нажатия кнопки*/
$_POST["save"][$id]=$id;


echo $this->partial("mf/catalog/admin/edittovar",[
                        "container"=>$this->container,
                        "new"=>$flagnew,
                        "torg"=>$this->torg
                        ]
                   );

